source 'https://rubygems.org'

gem 'active_model_serializers'
gem 'bcrypt', '3.1.11'
gem 'carrierwave', '~> 1.0'
gem 'devise'
gem 'jbuilder', '2.7.0'
gem 'jquery-rails'
gem 'kaminari'
gem 'mini_magick'
gem 'paranoia', '~> 2.2'
gem 'pg', '~> 0.18'
gem 'puma', '3.9.1'
gem 'rails', '5.1.4'
gem 'rails_admin', '~> 1.3'
gem 'ransack'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'sass-rails', '5.0.6'
gem 'simple_form'
gem 'turbolinks', '5.0.1'
gem 'typescript-rails'
gem 'uglifier', '3.2.0'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen',                '3.1.5'
  gem 'spring',                '2.0.2'
  gem 'spring-watcher-listen', '2.0.1'
  gem 'web-console',           '3.5.1'
end

group :test do
  gem 'byebug', '9.0.6', platform: :mri
  gem 'capybara'
  gem 'capybara-email'
  gem 'factory_bot_rails'
  gem 'guard', '2.13.0'
  gem 'guard-minitest', '2.4.4'
  gem 'launchy'
  gem 'minitest-reporters', '1.1.14'
  gem 'rails-controller-testing'
  gem 'rspec-rails', '~> 3.7'
  gem 'shoulda-matchers', ' ~> 3.1 '
end
